### PR TITLE
Valentine

### PR DESCRIPTION
**Pull request by NValentine-UWM**
Created all HTML pages and linked them all together.

### CODE REVIEW

**Comment by MWertel** [comment]
Looks good

**Comment by Dinossiah** [comment]
Approved

**Comment by danzzu** [comment]
Please do not merge Home.html. It is completed, if you merge we will have to revision.

**Comment by NValentine-UWM** [comment]
> Please do not merge Home.html. It is completed, if you merge we will have to revision.

Home isn't included in the files I did so it wont overwrite since I didn't touch that one

**Pull request merged**
